"""Added stage number.

Revision ID: 04475f626d6b
Revises: de3a88efb8cc
Create Date: 2024-05-25 10:45:18.053340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04475f626d6b'
down_revision = 'de3a88efb8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_stage', schema=None) as batch_op:
        batch_op.drop_column('stage_number')

    # ### end Alembic commands ###
