"""Added field to pet.

Revision ID: 5dd9d13500a5
Revises: d2dd9f9862cb
Create Date: 2024-05-25 17:22:33.032504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd9d13500a5'
down_revision = 'd2dd9f9862cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
