"""Changed date create to automatic.

Revision ID: d2dd9f9862cb
Revises: 04475f626d6b
Create Date: 2024-05-25 11:19:11.993043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2dd9f9862cb'
down_revision = '04475f626d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('treatment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostic', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_plan', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('diagnostic')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
